export enum ActionTypes {
   ENTRY_SUMBIT,
   CONTENT_EDITOR_BLUR,
   TAG_CHOSEN,
   AS_TYPING_TAGS,
   TAG_REMOVAL,
   INVALID_SUBMIT,
   AS_TYPING_TITLE,
   TITLE_BLUR,
   AS_TYPING_DATE,
   DATE_BLUR 
}